import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import Navbar from "./_components/Navbar/Navbar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang='en'>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          {
            <main className=' min-h-screen w-full bg-muted/40'>
              <Navbar />
              <div className="sm:ml-20 ">{children}</div>
            </main>
          }
        </TRPCReactProvider>
      </body>
    </html>
  );
}
